import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, ClipboardList, FileText, MapPin, RefreshCw, Search, UserRound } from 'lucide-react';
import type { CampaignRun } from '../types';
import { getActiveCampaignRuns, getMerchantArchives, getMerchantCampaign, MERCHANT_CAMPAIGN_START, merchantTodayIso, type MerchantArchiveSummary, type MerchantTeamActivity } from '../utils/merchantCampaign';
import { DateRangeKnobSlider } from './DateRangeKnobSlider';
import { MerchantBAOperationsModal } from './Modals/MerchantBAOperationsModal';

type MerchantOperation = 'profile' | 'report' | 'location' | 'calendar';

export const MerchantSupervisorArchivesView: React.FC = () => {
  const [run, setRun] = useState<CampaignRun | null>(null);
  const [archives, setArchives] = useState<MerchantArchiveSummary[]>([]);
  const [startDate, setStartDate] = useState(MERCHANT_CAMPAIGN_START);
  const [endDate, setEndDate] = useState(merchantTodayIso());
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [operation, setOperation] = useState<{ mode: MerchantOperation; activity: MerchantTeamActivity } | null>(null);

  const load = async () => {
    setLoading(true); setError('');
    try {
      const campaign = await getMerchantCampaign();
      if (!campaign) throw new Error('La campagne Merchant Educational Campaign est introuvable.');
      const runs = await getActiveCampaignRuns(campaign.id);
      const activeRun = runs.find((item) => item.status === 'active') || runs[0] || null;
      setRun(activeRun); setArchives(activeRun ? await getMerchantArchives(activeRun.id, startDate, endDate) : []);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Chargement des archives Merchant impossible.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [startDate, endDate]);

  const filtered = useMemo(() => { const needle = query.trim().toLowerCase(); return archives.filter((item) => !needle || `${item.ba.name} ${item.ba.phone} ${item.attendance.activity_date} ${item.attendance.closing_comment || ''}`.toLowerCase().includes(needle)); }, [archives, query]);
  const totals = useMemo(() => ({ reports: archives.length, pos: archives.reduce((total, item) => total + item.visitedPosCount, 0), transactions: archives.reduce((total, item) => total + item.transactionCount, 0), amount: archives.reduce((total, item) => total + item.totalAmount, 0) }), [archives]);
  const activityFor = (item: MerchantArchiveSummary): MerchantTeamActivity => ({ ba: item.ba, attendance: item.attendance, transactions: item.transactions, status: 'closed', visitedPosCount: item.visitedPosCount, inactivePosCount: 0, transactionCount: item.transactionCount, totalAmount: item.totalAmount, mfsNames: item.attendance.mfs_name ? [item.attendance.mfs_name] : [] });
  const actionButton = (activity: MerchantTeamActivity, mode: MerchantOperation, label: string, Icon: React.ElementType) => <button type="button" key={mode} onClick={() => setOperation({ mode, activity })} title={label} className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/10 bg-white/[0.05] text-gray-200 transition hover:border-amber-300/35 hover:bg-amber-400/10 hover:text-amber-100"><Icon size={16}/></button>;

  if (loading) return <div className="glass-card p-6 text-center text-xs font-black uppercase tracking-widest text-gray-400">Chargement des archives Merchant…</div>;
  return <div className="space-y-4 pb-4">
    <section className="glass-card relative overflow-hidden p-4"><div className="pointer-events-none absolute -right-12 -top-12 h-48 w-48 rounded-full bg-amber-400/[0.08] blur-3xl"/><div className="relative flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-amber-200/70">Archives de rapports</p><h1 className="mt-1 text-xl font-black">Merchant Educational Campaign</h1><p className="mt-1 text-xs text-gray-400">Journées clôturées et preuves terrain</p></div><button onClick={() => void load()} className="rounded-2xl border border-white/10 bg-white/5 p-3 text-gray-300"><RefreshCw size={17}/></button></div><div className="mt-4 grid grid-cols-4 gap-2 text-center"><div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-2"><b className="block text-sm text-white">{totals.reports}</b><span className="text-[8px] font-black uppercase text-gray-500">Rapports</span></div><div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-2"><b className="block text-sm text-cyan-100">{totals.pos}</b><span className="text-[8px] font-black uppercase text-gray-500">POS</span></div><div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-2"><b className="block text-sm text-amber-100">{totals.transactions}</b><span className="text-[8px] font-black uppercase text-gray-500">Transactions</span></div><div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-2"><b className="block text-sm text-emerald-100">{totals.amount.toLocaleString('fr-FR')}</b><span className="text-[8px] font-black uppercase text-gray-500">Montant</span></div></div></section>
    {error && <div className="rounded-2xl border border-red-400/40 bg-red-950/45 p-3 text-xs font-bold text-red-100">{error}</div>}
    <section className="glass-card space-y-3 p-4"><div className="flex items-center gap-2"><CalendarDays className="text-amber-200" size={19}/><div><h2 className="font-black">Période de consultation</h2><p className="text-xs text-gray-400">Filtrez les rapports journaliers réellement clôturés.</p></div></div><DateRangeKnobSlider minDate={MERCHANT_CAMPAIGN_START} maxDate={merchantTodayIso()} startDate={startDate} endDate={endDate} onChange={({ startDate: nextStart, endDate: nextEnd }) => { setStartDate(nextStart); setEndDate(nextEnd); }} /><div className="relative"><Search className="absolute left-3 top-3.5 text-gray-500" size={16}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="BA, téléphone, date ou commentaire" className="app-input w-full rounded-2xl py-3 pl-10 pr-4 text-sm"/></div></section>
    <section className="space-y-3">{filtered.map((item) => { const activity = activityFor(item); const arrival = item.attendance.checkin_at ? new Date(item.attendance.checkin_at).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' }) : '—'; const departure = item.attendance.checkout_at ? new Date(item.attendance.checkout_at).toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' }) : '—'; return <article key={item.attendance.id} className="glass-card p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-amber-200">{new Date(`${item.attendance.activity_date}T12:00:00`).toLocaleDateString('fr-FR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}</p><h3 className="mt-1 truncate font-black text-white">{item.ba.name}</h3><p className="mt-0.5 text-xs text-gray-400">{item.ba.phone} · {arrival} → {departure}</p></div><div className="flex shrink-0 items-center gap-1.5">{actionButton(activity, 'profile', 'Détail BA', UserRound)}{actionButton(activity, 'report', 'Aperçu rapport', FileText)}{actionButton(activity, 'location', 'Carte GPS intégrée', MapPin)}{actionButton(activity, 'calendar', 'Calendrier présence', CalendarDays)}<span className="ml-1 inline-flex items-center gap-1 rounded-xl border border-emerald-400/35 bg-emerald-500/15 px-2.5 py-1 text-[10px] font-black uppercase text-emerald-200"><CheckCircle2 size={14}/>Clôturé</span></div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-2"><b className="block text-sm text-cyan-100">{item.visitedPosCount}</b><span className="text-[8px] font-black uppercase text-gray-500">POS</span></div><div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-2"><b className="block text-sm text-amber-100">{item.transactionCount}</b><span className="text-[8px] font-black uppercase text-gray-500">Transactions</span></div><div className="rounded-2xl border border-white/[0.08] bg-white/[0.04] p-2"><b className="block text-sm text-emerald-100">{item.totalAmount.toLocaleString('fr-FR')}</b><span className="text-[8px] font-black uppercase text-gray-500">Montant</span></div></div>{item.attendance.closing_comment && <div className="mt-3 rounded-2xl border border-white/[0.08] bg-white/[0.03] p-3 text-xs text-gray-300"><div className="mb-1 flex items-center gap-2 text-[10px] font-black uppercase text-gray-500"><ClipboardList size={13}/>Commentaire BA</div>{item.attendance.closing_comment}</div>}</article>; })}{filtered.length === 0 && <div className="glass-card p-7 text-center"><ClipboardList className="mx-auto text-gray-500" size={26}/><h2 className="mt-3 font-black">Aucun rapport clôturé</h2><p className="mt-1 text-xs text-gray-400">Les archives apparaîtront après la clôture d’une journée BA dans la période sélectionnée.</p></div>}</section>
    <MerchantBAOperationsModal isOpen={Boolean(operation)} mode={operation?.mode || 'profile'} activity={operation?.activity || null} run={run} onClose={() => setOperation(null)}/>
  </div>;
};
